apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-southeast-1.amazonaws.com/abc:latest-6a4e04bb78ab81c754412710662bbe46e2b1983a
        name: java-api
        ports:
        - containerPort: 8080
