apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-south-1.amazonaws.com/java-api:e80ebcf0437bcf349dd201cd3d4891de665e740c
        name: java-api
        ports:
        - containerPort: 8080
