apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-south-1.amazonaws.com/java-api:c5270e8905b93f1eaf05095686331f8bf13fc3df
        name: java-api
        ports:
        - containerPort: 8080
