apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-south-1.amazonaws.com/abc:latest-a000c311565e23656dc95efe599e08f8183306a2
        name: java-api
        ports:
        - containerPort: 80
