apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-southeast-1.amazonaws.com/abc:latest-7fdd543aba75335e17910a44183f997f217609c6
        name: java-api
        ports:
        - containerPort: 8080
