apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
      - image: 485229547579.dkr.ecr.ap-south-1.amazonaws.com/abc:2d8d57f5e1a275a940af29a64e15bbfaae4e7c59
        name: java-api
        ports:
        - containerPort: 80
